### ISSUE TITLE
File browser throws errors when opening folder without correct premissions

### ISSUE THREAD

**Issue by Kad1n** [tomrtk/fish-code#140]
Selecting a folder without sufficient read premissions results in a ASGI stacktrace error message in the terminal. The API still works after the crash, but this should be handled more neatly in `get_directory_listing()` or `get_storage_path()`.

In order to reproduce, launch the application and navigate to the UI in the file browser. Create a project, then open the job creation window in the new project. Try to expand any folder with insufficient read permissions, for example `/root` on Linux systems. (Unless you are the root user) This should show the following stacktrace in the terminal.

```
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 216, in app
    raw_response = await run_endpoint_function(
  File "/home/kad/Projects/Git/code/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/kad/Projects/Git/code/src/core/api/api.py", line 665, in get_storage_path
    return get_directory_listing(decrypted_path)
  File "/home/kad/Projects/Git/code/src/core/services.py", line 613, in get_directory_listing
    for p in normalized_path.iterdir():
  File "/usr/lib64/python3.8/pathlib.py", line 1122, in iterdir
    for name in self._accessor.listdir(self):
PermissionError: [Errno 13] Permission denied: '/root'
```

**Comment by MindTooth** [comment]
One option to deal with this in the UI is to supply the request with a [`error()`](https://api.jquery.com/jquery.ajax/#jQuery-ajax-settings) function on the request.  So when we return e.g. permission denied ([403](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403)), we can then disable the node and perhaps change the icon to an X or something.

Example of what it could become:

<img width="179" alt="Screen Shot 2021-07-29 at 13 04 42" src="https://user-images.githubusercontent.com/33870508/127481625-1a6b92a7-c367-4ca5-942d-8acabb8e647a.png">

I'm struggling with e.g. renaming the node to perhaps notice the user that its permission denied.

**Comment by MindTooth** [comment]
<img width="389" alt="Screen Shot 2021-07-29 at 15 15 55" src="https://user-images.githubusercontent.com/33870508/127498641-f2c1ee3d-6d24-43ae-ba24-a6a81e349c39.png">

Another take.
