### ISSUE TITLE
Running in a non-graphical environment not working

### ISSUE THREAD

**Issue by tomrtk** [tomrtk/fish-code#199]
## Issue

Running `nina` on a server or docker container without a graphical environment fails.

## Reproduction

Run `nina` in a `ubuntu:latest` docker container.

```consol
Traceback (most recent call last):
  File "/tmp/test/venv/bin/nina", line 5, in <module>
    from nina.run import main
  File "/tmp/test/venv/lib/python3.8/site-packages/nina/run.py", line 8, in <module>
    from core.main import main as core_main  # type: ignore
  File "/tmp/test/venv/lib/python3.8/site-packages/core/main.py", line 13, in <module>
    import core.api
  File "/tmp/test/venv/lib/python3.8/site-packages/core/api/__init__.py", line 3, in <module>
    from .api import *
  File "/tmp/test/venv/lib/python3.8/site-packages/core/api/api.py", line 25, in <module>
    import core.api.schema as schema
  File "/tmp/test/venv/lib/python3.8/site-packages/core/api/schema.py", line 7, in <module>
    from core import model
  File "/tmp/test/venv/lib/python3.8/site-packages/core/model.py", line 23, in <module>
    import cv2 as cv
  File "/tmp/test/venv/lib/python3.8/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

## Possible solution

Change to use `opencv-python-headless` package instead. I believe this should work as we do note use any graphical elements from `opencv`, but it would need to be tested on all platforms.

**Comment by MindTooth** [comment]
Maybe we should look at building an image too.  Hosting it here on the project.

Nice catch!
