### ISSUE TITLE
Update install instructions to mention newer setupstools

### ISSUE THREAD

**Issue by MindTooth** [tomrtk/fish-code#319]
It seems that [v60.x](https://setuptools.pypa.io/en/latest/history.html#v60-0-0) of setuptools broke installation.  To get around this, the user needs to prepend `SETUPTOOLS_USE_DISTUTILS=stdlib` before the install commando.  E.g.:

```
SETUPTOOLS_USE_DISTUTILS=stdlib python3 -m pip install -e .[CPU]
```

**Comment by tomrtk** [comment]
Should also update docs to use correct url to torch package index in `pip install` commands as of `torch 1.10.X` as given [here](https://pytorch.org/get-started/locally/).

**Comment by tomrtk** [comment]
> Should also update docs to use correct url to torch package index in `pip install` commands as of `torch 1.10.X` as given [here](https://pytorch.org/get-started/locally/).

Also it should be verified working with `gpu`. I do not have easy access to `gpu` on a windows machine.

When this is done, we should release a new version, to make sure the docs is correct for the wheel in release artifact.

**Comment by tomrtk** [comment]
> It seems that [v60.x](https://setuptools.pypa.io/en/latest/history.html#v60-0-0) of setuptools broke installation. To get around this, the user needs to prepend `SETUPTOOLS_USE_DISTUTILS=stdlib` before the install commando. E.g.:
> 
> ```
> SETUPTOOLS_USE_DISTUTILS=stdlib python3 -m pip install -e .[CPU
> ```

I tested this today, and I did not meet this issue. So I did a test in an ubuntu container as well, without needing to use this workaround.

```consol
❯ docker run -v $PWD:/fish/ -i -t ubuntu
root@f18524590310:/# cd fish/
root@f18524590310:/fish# apt update && apt install python3 git python3.8-venv
root@f18524590310:/fish# python3 -m venv venv
root@f18524590310:/fish# . venv/bin/activate
(venv) root@f18524590310:/fish# pip install pip --upgrade
(venv) root@f18524590310:/fish# pip install -e .[cpu]
```

Is this a mac issue or was it a bug in first release of setuptools 60 maybe?

**Comment by MindTooth** [comment]
I believe it’s the reason why the pipeline failes too.

https://github.com/MindTooth/fish-code/runs/4650419081?check_suite_focus=true

**Comment by MindTooth** [comment]
I’ll draft up something this weekend.  I also need a Windows machine with GPU.  @Kad1n can test maybe?

**Comment by MindTooth** [comment]
> > It seems that [v60.x](https://setuptools.pypa.io/en/latest/history.html#v60-0-0) of setuptools broke installation. To get around this, the user needs to prepend `SETUPTOOLS_USE_DISTUTILS=stdlib` before the install commando. E.g.:
> > ```
> > SETUPTOOLS_USE_DISTUTILS=stdlib python3 -m pip install -e .[CPU
> > ```
> 
> I tested this today, and I did not meet this issue. So I did a test in an ubuntu container as well, without needing to use this workaround.
> 
> ```
> ❯ docker run -v $PWD:/fish/ -i -t ubuntu
> root@f18524590310:/# cd fish/
> root@f18524590310:/fish# apt update && apt install python3 git python3.8-venv
> root@f18524590310:/fish# python3 -m venv venv
> root@f18524590310:/fish# . venv/bin/activate
> (venv) root@f18524590310:/fish# pip install pip --upgrade
> (venv) root@f18524590310:/fish# pip install -e .[cpu]
> ```
> 
> Is this a mac issue or was it a bug in first release of setuptools 60 maybe?

https://github.com/pypa/setuptools/issues/2980 fixed it maybe?

**Comment by tomrtk** [comment]
Possible. I believe the issue in the pipeline is poetry used by [sort](https://github.com/R0flcopt3r/sort/), related to the same update of setuptools.

From the stacktrace it is related to poetry at leased.

**Comment by MindTooth** [comment]
A newer version of setuptools fixed this.

Closing as a blip.

**Comment by MindTooth** [comment]
```
$ pip install -e .[gpu] --find-links https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Obtaining file:///C:/Users/Birger%20J.%20Nord%C3%B8lum/Downloads/fish-code-master
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting sort@ https://github.com/R0flcopt3r/sort/tarball/12e0602e99b11bac49ae48a53f25d60cf37b8c72
  Downloading https://github.com/R0flcopt3r/sort/tarball/12e0602e99b11bac49ae48a53f25d60cf37b8c72 (734 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\cli\base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\commands\install.py", line 338, in run
    requirement_set = resolver.resolve(
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 482, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 374, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 214, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 204, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 204, in get_dependencies
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 204, in <listcomp>
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 490, in iter_dependencies
    requirement = factory.make_requirement_from_spec(
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 491, in make_requirement_from_spec
    return self._make_requirement_from_install_req(ireq, requested_extras)
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 430, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 201, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 281, in __init__
    super().__init__(
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 292, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\operations\prepare.py", line 482, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\operations\prepare.py", line 546, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\operations\prepare.py", line 58, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\distributions\sdist.py", line 47, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\distributions\sdist.py", line 106, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\distributions\sdist.py", line 83, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\wrappers.py", line 172, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\wrappers.py", line 332, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 89, in _build_backend
    obj = import_module(mod_path)
  File "C:\Users\Birger J. Nord▒lum\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'poetry'
```

Well. 🤔  Either we inline our fork of sort, require `poetry`, or change sort to be setup.cfg?

---

Also, the same installation instructions are valid when referring to the same `--find-links` URL.

**Comment by R0flcopt3r** [comment]
I say we take the easy way out and bundle it.

**Comment by MindTooth** [comment]
> I say we take the easy way out and bundle it.

You do?
